var graduates = {
    "2016": [
        { name: 'Abdelrahman Refaat', image: '' },
        { name: 'Abdelrahman Mady', image: '' },
        { name: 'Adham Shady', image: '' },
        { name: 'Ahmed Hossam', image: '' },
        { name: 'Ahmed Kamar', image: '' },
        { name: 'Ahmed Ossama', image: '' },
        { name: 'Ahmed Salah', image: '' },
        { name: 'Aya Mohi', image: '' },
        { name: 'Basma Mohamed Kassem', image: '' },
        { name: 'Ezzelden Mohamed Elmasre', image: '' },
        { name: 'Fatma Hamdy', image: '' },
        { name: 'Hana Ghanem', image: '' },
        { name: 'Kirollos Adel', image: '' },
        { name: 'Lina Samy', image: '' },
        { name: 'Mahmoud Alshemy', image: '' },
        { name: 'Mahmoud Gamal', image: '' },
        { name: 'Malak Farhoud', image: '' },
        { name: 'Mark Adel', image: '' },
        { name: 'Marwan Fouda', image: '' },
        { name: 'Mazen AboelHassan', image: '' },
        { name: 'Menna Nabil', image: '' },
        { name: 'Mina Ramiz', image: '' },
        { name: 'Mohamed AbdelMoniem', image: '' },
        { name: 'Mohamed AbdelSamie', image: '' },
        { name: 'Mohamed Ashraf', image: '' },
        { name: 'Mostafa Magdy', image: '' },
        { name: 'Moustafa Omar', image: '' },
        { name: 'Nermiin Evie', image: '' },
        { name: 'Noha Haydak', image: '' },
        { name: 'Nourhan Farouk', image: '' },
        { name: 'Omar Hisham', image: '' },
        { name: 'Pola Ehab', image: '' },
        { name: 'Ramez Aziz', image: '' },
        { name: 'Rewan Rony', image: '' },
        { name: 'Salah Kamal', image: '' },
        { name: 'Salma Amr', image: '' },
        { name: 'Salma Hisham', image: '' },
        { name: 'Sara Tarek Mohamed', image: '' },
        { name: 'Sayfnaz Tarek', image: '' },
        { name: 'Shahd Mahmoud Mohamed', image: '' },
        { name: 'Toka Sherif', image: '' },
        { name: 'Waled Mostafa Aly', image: '' },
        { name: 'Yosra Emad', image: '' },
        { name: 'Youssef Reda', image: '' }
    ],
    "2015": [

    ]
}
